test:
    host: 'localhost'
    port: 5432
    dbname: ''
    user: ''
    password: ''

development:
    host: 'localhost'
    port: 5432
    dbname: ''
    user: ''
    password: ''

production:
    host: 'localhost'
    port: 5432
    dbname: ''
    user: ''
    password: ''
